services:
  postgres_kestrel:
    image: postgres:16.4-alpine3.20
    container_name: kestrel_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=counterside
      - POSTGRES_USER=kestrel_user
      - POSTGRES_PASSWORD=magical_password
    volumes:
      - ./schema/counterside:/docker-entrypoint-initdb.d
      - counterside_db:/var/lib/postgresql/data
    tty: true
    restart: unless-stopped
    networks:
      - backend

volumes:
  counterside_db:
    driver: local

networks:
  backend:
    driver: bridge
