-- add custom sequence here
-- no need to create sequence manually anymore because
-- when you create a table with primary key of serial
-- data type family, it will also automatically create
-- a sequence with the format of <table_name>_<column_name>_seq
-- and assign its nextval
